### ISSUE TITLE
basic authentication with json registry config doesn't work

### ISSUE THREAD

**Issue by edio** [uber/makisu#167]
In our company we use artifactory with anonymous downloads allowed. To be able to fetch a base image I use following `makisu.yaml` and it works just fine
```
artifactory.mycompany.com:
  docker-registry:
    security:
      tls:
        client:
          disabled: true
      basic:
        username: ""
        password: ""
```

But being converted to json it just won't work
```
{ "artifactory.mycompany.com": { "docker-registry": { "security": { "tls": { "client": { "disabled": true } }, "basic": { "username": "", "password": "" } } } } }
```
I tried using `{}`s for empty values, tried removing `basic` block, etc.. It never works.

Seems, that json mapping is broken.

Let me know, if any other details are needed to reproduce this.

May be related to #157
